### ISSUE TITLE
How to get the files in the "ir_zoos" directory which used in mcu_ir_gen.py ?

### ISSUE THREAD

**Issue by VisionShilin** [mit-han-lab/tiny-training#8]
How to get the files in the "ir_zoos" directory which used in mcu_ir_gen.py ?

**Comment by Lyken17** [comment]
This is a output directory rather than model checkpoints as you can find in https://github.com/mit-han-lab/tiny-training/blob/main/compilation/mcu_ir_gen.py#L88

Once you run the scripts, corresponding IRs will be generated under `ir_zoos`

**Comment by VisionShilin** [comment]
Thanks.
